### ISSUE TITLE
Crashed in aarch64

### ISSUE THREAD

**Issue by dutor** [facebook/folly#1347]
I maganged to cross compile folly(v2018.08.20) for Raspberry Pi 4 from a x64 box, along with an application that takes advantage of folly. But the application crashed in the target environment. 

Here is the backtrace:
```
#0  __GI_raise ()
#1  0x0000ffffa89ecfa8 in __GI_abort ()
#2  0x000000000053d810 in uw_init_context_1 ()
#3  0x000000000053de68 in _Unwind_RaiseException () 
#4  0x00000000004e6d14 in __cxxabiv1::__cxa_throw () 
#5  0x0000000000453a98 in folly::CacheLocality::readFromSysfsTree()
    at folly/concurrency/CacheLocality.cpp:146
#6  0x0000000000453c28 in folly::CacheLocality::readFromSysfs () at folly/concurrency/CacheLocality.cpp:187
#7  folly::CacheLocality::system<std::atomic> () at folly/concurrency/CacheLocality.cpp:39
#8  0x0000000000455630 in folly::AccessSpreader<std::atomic>::initialize () at folly/concurrency/CacheLocality.h:305
#9  0x000000000040e97c in __static_initialization_and_destruction_0 (__priority=65535, __initialize_p=1) at folly/concurrency/CacheLocality.h:335
#10 _GLOBAL__sub_I__ZN5folly13CacheLocality6systemISt6atomicEERKS0_v () at folly/concurrency/CacheLocality.cpp:269
#11 0x000000000053fcf8 in __libc_csu_init ()
#12 0x0000ffffa89ed394 in __libc_start_main () 
#13 0x000000000040f594 in _start () 
```

And here are some additional infos that might help:
```
ubuntu@ubuntu:~$ uname -a
Linux ubuntu 5.3.0-1014-raspi2 #16-Ubuntu SMP Tue Nov 26 11:18:23 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
ubuntu@ubuntu:~$ tree /sys/devices/system/cpu/cpu0/
/sys/devices/system/cpu/cpu0/
├── cpu_capacity
├── cpufreq -> ../cpufreq/policy0
├── crash_notes
├── crash_notes_size
├── hotplug
│   ├── fail
│   ├── state
│   └── target
├── of_node -> ../../../../firmware/devicetree/base/cpus/cpu@0
├── online
├── power
│   ├── async
│   ├── autosuspend_delay_ms
│   ├── control
│   ├── pm_qos_resume_latency_us
│   ├── runtime_active_kids
│   ├── runtime_active_time
│   ├── runtime_enabled
│   ├── runtime_status
│   ├── runtime_suspended_time
│   └── runtime_usage
├── regs
│   └── identification
│       ├── midr_el1
│       └── revidr_el1
├── subsystem -> ../../../../bus/cpu
├── topology
│   ├── core_cpus
│   ├── core_cpus_list
│   ├── core_id
│   ├── core_siblings
│   ├── core_siblings_list
│   ├── die_cpus
│   ├── die_cpus_list
│   ├── die_id
│   ├── package_cpus
│   ├── package_cpus_list
│   ├── physical_package_id
│   ├── thread_siblings
│   └── thread_siblings_list
└── uevent

```

**Comment by Orvid** [comment]
We can't provide support for a 1.5 year old version of Folly unfortunately. If this still reproduces on the most recent version, then we can look into it.

**Comment by dutor** [comment]
> We can't provide support for a 1.5 year old version of Folly unfortunately. If this still reproduces on the most recent version, then we can look into it.

Yes, I have found that the lastest version works well. In case any others might encount this problem, [this patch](https://github.com/facebook/folly/commit/60be5ec6d5b85c89cadd6ff9a986fa59e88b714d) could fix it.
