### ISSUE TITLE
pod install failed with Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h

### ISSUE THREAD

**Issue by zjkuang** [facebook/folly#1575]
Running `pod install` failed with message
```
% pod install               
...
Downloading dependencies
...
Installing FBReactNativeSpec 0.64.1 (was 0.64.0)
Installing Flipper-Folly 2.5.3 (was 2.6.3)
Installing Flipper-RSocket 1.3.1 (was 1.4.1)
...
Installing RCTRequired 0.64.1 (was 0.64.0)
Installing RCTTypeSafety 0.64.1 (was 0.64.0)
...
Installing React 0.64.1 (was 0.64.0)
Installing React-Core 0.64.1 (was 0.64.0)
...
Installing react-native-flipper 0.88.0 (was 0.87.0)
...
Generating Pods project
Patching .../ios/Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h
[!] An error occurred while processing the post-install hook of the Podfile.

Permission denied @ rb_sysopen - .../packages/mobile-app/ios/Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h

.../node_modules/react-native/scripts/react_native_pods.rb:228:in `initialize'
.../node_modules/react-native/scripts/react_native_pods.rb:228:in `open'
.../node_modules/react-native/scripts/react_native_pods.rb:228:in `block in find_and_replace'
.../node_modules/react-native/scripts/react_native_pods.rb:221:in `each'
.../node_modules/react-native/scripts/react_native_pods.rb:221:in `find_and_replace'
.../node_modules/react-native/scripts/react_native_pods.rb:148:in `react_native_post_install'
.../packages/SharedPodfile.rb:58:in `block in flipper'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:897:in `run_podfile_post_install_hook'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:885:in `block in run_podfile_post_install_hooks'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:884:in `run_podfile_post_install_hooks'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:329:in `block (2 levels) in create_and_save_projects'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:328:in `block in create_and_save_projects'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.10.1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.10.1/libexec/bin/pod:23:in `<main>'
```

**Comment by ricbermo** [comment]
`rm -rf ./Pods/ && pod install --repo-update` did the trick

**Comment by MuhammadAbdullah54321** [comment]
> `rm -rf ./Pods/ && pod install --repo-update` did the trick

this will throw this error
[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/deprecated_podspecs.txt Response: 403 <!DOCTYPE html> ......

**Comment by MuhammadAbdullah54321** [comment]
I tried this solution and it worked
Simply delete the Pod folder inside ios folder.
then run the command "pod install"
