### ISSUE TITLE
List index out of range: build error

### ISSUE THREAD

**Issue by B3rK-3** [facebook/folly#2277]
`C:\Users\josbu\OneDrive\Documents\GitHub\FastFile-File-Browser\folly>build.bat
Mapping scratch dir C:\Users\josbu\AppData\Local\Temp\fbcode_builder_getdeps-CZZUsersZjosbuZOneDriveZDocumentsZGitHubZFastFile-File-BrowserZfollyZbuildZfbcode_builder -> Z:\
Traceback (most recent call last):
  File "C:\Users\josbu\OneDrive\Documents\GitHub\FastFile-File-Browser\folly\\build\fbcode_builder\getdeps.py", line 1422, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\josbu\OneDrive\Documents\GitHub\FastFile-File-Browser\folly\\build\fbcode_builder\getdeps.py", line 1405, in main
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "C:\Users\josbu\OneDrive\Documents\GitHub\FastFile-File-Browser\folly\\build\fbcode_builder\getdeps.py", line 74, in run
    opts = setup_build_options(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\josbu\OneDrive\Documents\GitHub\FastFile-File-Browser\folly\build\fbcode_builder\getdeps\buildopts.py", line 659, in setup_build_options
    return BuildOptions(
           ^^^^^^^^^^^^^
  File "C:\Users\josbu\OneDrive\Documents\GitHub\FastFile-File-Browser\folly\build\fbcode_builder\getdeps\buildopts.py", line 165, in __init__
    vcvars_path = vcvarsall[0]
                  ~~~~~~~~~^^^
IndexError: list index out of range`

I have tried the lastest version and the one before but none have worked.
cmake version 3.30.2
gcc and g++: 14.1.0
python 3.12.6

**Comment by shy-ing** [comment]
I am also facing the same problem. Did you fix it?

**Comment by B3rK-3** [comment]
I wasn't able to so I switched libraries.

**Comment by lineagedr** [comment]
I had the same issue on Windows 11, VS2022 just don't use build.bat, instead use vcpkg.

https://github.com/facebook/folly?tab=readme-ov-file#windows-vcpkg
