### ISSUE TITLE
dry run of install-system-deps fails without sudo

### ISSUE THREAD

**Issue by gmarzot** [facebook/folly#2353]
documentation shows the command run without sudo. ideally sudo should only be required for specific operations and anything that does need to be run as root would run as user.

gmarzot@GMARZOT-LAPTOP:~/Projects/moq/folly$ ./build/fbcode_builder/getdeps.py install-system-deps --dry-run --recursive
Traceback (most recent call last):
  File "/home/gmarzot/Projects/moq/folly/./build/fbcode_builder/getdeps.py", line 1484, in <module>
    sys.exit(main())
  File "/home/gmarzot/Projects/moq/folly/./build/fbcode_builder/getdeps.py", line 1467, in main
    return args.func(args)
  File "/home/gmarzot/Projects/moq/folly/./build/fbcode_builder/getdeps.py", line 74, in run
    opts = setup_build_options(args)
  File "/home/gmarzot/Projects/moq/folly/build/fbcode_builder/getdeps/buildopts.py", line 591, in setup_build_options
    subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'mkscratch'

**Comment by gmarzot** [comment]
specifying writable --scratch-path can avoid sudo so perhaps this is just a doc issue. and prseumable one can build this way after pkg installs.

(uv) gmarzot@GMARZOT-LAPTOP:~/Projects/moq/folly$ ./build/fbcode_builder/getdeps.py install-system-deps --dry-run --recu
rsive --scratch-path /tmp/folly
sudo apt install -y autoconf automake binutils-dev cmake libboost-all-dev libdouble-conversion-dev libdwarf-dev libevent-dev libgflags-dev liblz4-dev libsnappy-dev libsodium-dev libtool libzstd-dev ninja-build zlib1g-dev zstd
