### ISSUE TITLE
Server was stuck

### ISSUE THREAD

**Issue by tian-yuan** [facebook/folly#444]
hello,

My server was stuck after running 12hours；

Os info:
      Linux version 2.6.32 (root@xxxx) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Thu Apr 3 15:06:13 CST 2014

folly version : v0.57.0

pstack info ：
$ pstack 10973
Thread 20 (Thread 0x7fbe1c7ff700 (LWP 10975)):
#0  0x00007fbe1d492178 in _Unwind_IteratePhdrCallback () from /usr/local/lib64/libgcc_s.so.1
#1  0x00007fbe1d1fb8c4 in dl_iterate_phdr () from /usr/local/lib/libc.so.6
#2  0x00007fbe1d4931d3 in _Unwind_Find_FDE () from /usr/local/lib64/libgcc_s.so.1
#3  0x00007fbe1d490494 in uw_frame_state_for () from /usr/local/lib64/libgcc_s.so.1
#4  0x00007fbe1d491283 in _Unwind_RaiseException () from /usr/local/lib64/libgcc_s.so.1
#5  0x00007fbe1d6f533b in __cxa_throw () from /usr/local/lib64/libstdc++.so.6
#6  0x0000000000b3ffb9 in folly::throwSystemErrorExplicit(int, char const*) ()
#7  0x0000000000f10ee3 in folly::SocketAddress::setFromSocket(int, int (*)(int, sockaddr*, unsigned int*)) ()
#8  0x0000000000ed8628 in folly::AsyncSocket::getPeerAddress(folly::SocketAddress*) const ()
#9  0x0000000000edad9e in folly::AsyncSocket::withAddr(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#10 0x0000000000ee040f in folly::AsyncSocket::handleRead() ()
#11 0x0000000000eddeca in folly::AsyncSocket::ioReady(unsigned short) ()
#12 0x0000000000f66acf in event_base_loop ()
#13 0x0000000000ef1657 in folly::EventBase::loopBody(int) ()
#14 0x0000000000ef1fb6 in folly::EventBase::loopForever() ()
#15 0x0000000000e3e2a2 in wangle::IOThreadPoolExecutor::threadRun(std::shared_ptr<wangle::ThreadPoolExecutor::Thread>) ()
#16 0x0000000000e4c22b in _ZNKSt7_Mem_fnIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS1_6ThreadEEEEclIJRS4_EvEEvPS1_DpOT_ ()
#17 0x0000000000e4ab1d in _ZNSt5_BindIFSt7_Mem_fnIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS2_6ThreadEEEEPS2_S5_EE6__callIvJEJLm0ELm1EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE ()
#18 0x0000000000e484dc in _ZNSt5_BindIFSt7_Mem_fnIMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS2_6ThreadEEEEPS2_S5_EEclIJEvEET0_DpOT_ ()
#19 0x0000000000e462e5 in std::_Function_handler<void ()(), std::_Bind<std::_Mem_fn<void (wangle::ThreadPoolExecutor::*)(std::shared_ptr<wangle::ThreadPoolExecutor::Thread>)> ()(wangle::ThreadPoolExecutor*, std::shared_ptr<wangle::ThreadPoolExecutor::Thread>)> >::_M_invoke(std::_Any_data const&) ()
#20 0x0000000000b431c2 in std::function<void ()()>::operator()() const ()
#21 0x0000000000c11580 in _ZNSt12_Bind_simpleIFSt8functionIFvvEEvEE9_M_invokeIJEEEvSt12_Index_tupleIJXspT_EEE ()
#22 0x0000000000c11311 in std::_Bind_simple<std::function<void ()()> ()()>::operator()() ()
#23 0x0000000000c1105a in std::thread::_Impl<std::_Bind_simple<std::function<void ()()> ()()> >::_M_run() ()
#24 0x00007fbe1d752690 in execute_native_thread_routine () from /usr/local/lib64/libstdc++.so.6
#25 0x00000038542079d1 in start_thread () from /lib64/libpthread.so.0
#26 0x00007fbe1d1c622d in clone () from /usr/local/lib/libc.so.6

LOG info ：
E0723 09:52:54.419632 10991 AsyncServerSocket.cpp:860] failed to dispatch newly accepted socket: all accept callback queues are full
E0723 09:52:54.486778 10991 AsyncServerSocket.cpp:860] failed to dispatch newly accepted socket: all accept callback queues are full
E0723 09:52:54.496165 10991 AsyncServerSocket.cpp:860] failed to dispatch newly accepted socket: all accept callback queues are full
E0723 09:52:54.506131 10991 AsyncServerSocket.cpp:860] failed to dispatch newly accepted socket: all accept callback queues are full
E0723 09:52:54.509289 10991 AsyncServerSocket.cpp:860] failed to dispatch newly accepted socket: all accept callback queues are full
E0723 09:52:54.531406 10991 AsyncServerSocket.cpp:860] failed to dispatch newly accepted socket: all accept callback queues are full

      other io thread was stuck except the accept thread, may be the socket can not be closed.

**Comment by tian-yuan** [comment]
we use libc.so is not thread safe，cause the problem
