### ISSUE TITLE
Segmentation fault EvictingCacheMap.h

### ISSUE THREAD

**Issue by trungnq97** [facebook/folly#742]
Hi all,
I got segmentation faults when using EvictingCacheMap. It doesn't happen all the time, but random (once every 2-3 days). Do you have any thought? Cheers.

```
(gdb) bt
#0  0x0000000000e92078 in boost::intrusive::list_node_traits<void*>::set_next (
    n=@0x7f7127f80880: 0x0, next=@0x7f7127f808b0: 0x7f7125fbfaf8)
    at /usr/local/include/boost/intrusive/detail/list_node.hpp:66
#1  0x0000000000ea0704 in boost::intrusive::circular_list_algorithms<boost::intrusive::list_node_traits<void*> >::link_before (nxt_node=@0x7f7127f808c0: 0x7f7125fbfaf8,
    this_node=@0x7f7127f808b0: 0x7f7125fbfaf8)
    at /usr/local/include/boost/intrusive/circular_list_algorithms.hpp:182
#2  0x0000000000e9ee11 in boost::intrusive::list_impl<boost::intrusive::bhtraits<folly::EvictingCacheMap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<...>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::Node, boost::intrusive::list_node_traits<void*>, (boost::intrusive::link_mode_type)1, boost::intrusive::dft_tag, 1u>, unsigned long, true, void>::push_front (this=0x7f712fe093e8, value=...)
    at /usr/local/include/boost/intrusive/list.hpp:290
#3  0x0000000000e9c298 in folly::EvictingCacheMap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<...>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::find
    (this=0x7f712fe09390, key=...)
    at /usr/local/include/folly/container/EvictingCacheMap.h:231
```

**Comment by trungnq97** [comment]
The rootcause is multithreads access the cache at the same time. I'll close this issue now.
